### ISSUE TITLE
Display Icons Depending on Weather 🙏 

### ISSUE THREAD

**Issue by abigailelizabeth** [JustinSaenz/just-weather#2]

**Comment by abigailelizabeth** [comment]
☁️ 🌩️ ⛈️ 🌧️ 🌨️ 🌥️ 🌦️ 🌤️ 🌞 ☀️ ⛅

**Comment by jasonjalufka** [comment]
Here's a link describing what the weather conditions are and how to get the corresponding icons

https://openweathermap.org/weather-conditions

**Comment by jasonjalufka** [comment]
@JustinSaenz How are you planning on rendering/displaying the icons? 🤔
